apiVersion: v1
kind: Service
metadata:
  name: service-clusterip
  namespace: dev
spec: 
  selector:
    app: nginx-pod
  clusterIP: 10.97.97.97
  type: ClusterIP
  sessionAffinity: ClientIP
  ports:
    - port: 80
      targetPort: 80