apiVersion: v1
kind: Pod
metadata:
  name: pod-podaffinity-required
  namespace: dev
spec:
  containers:
  - name: nginx
    image: nginx:1.17.1
  affinity:  #亲和性设置
    podAffinity: #设置pod亲和性
      requiredDuringSchedulingIgnoredDuringExecution: # 硬限制
      - labelSelector:
          matchExpressions: # 匹配env的值在["xxx"]中的标签
          - key: podenv
            operator: In
            values: ["pro"]
        namespaces:
        - dev
        namespaceSelector:
          matchLabels:
            environment: production
        topologyKey: kubernetes.io/hostname